apiVersion: v1
kind: Service
metadata:
  name: posts-node-port-srv
  namespace: dev-01
spec: 

  type: NodePort
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: posts

# In terminal:
# kubectl apply -f name.yaml
# kubectl create namespace dev-01